/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library calculadora;

export 'src/calculadora.dart' show Calculadora;
export 'src/calculadora.dart' show CalculadoraClient;
export 'src/calculadora.dart' show CalculadoraProcessor;
