#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Funcion_cuadratica; end

class Funcion_cuadratica
  include ::Thrift::Struct, ::Thrift::Struct_Union
  A = 1
  B = 2
  C = 3
  X1 = 4
  X2 = 5

  FIELDS = {
    A => {:type => ::Thrift::Types::I32, :name => 'a'},
    B => {:type => ::Thrift::Types::I32, :name => 'b'},
    C => {:type => ::Thrift::Types::I32, :name => 'c'},
    X1 => {:type => ::Thrift::Types::DOUBLE, :name => 'x1'},
    X2 => {:type => ::Thrift::Types::DOUBLE, :name => 'x2'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field a is unset!') unless @a
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field b is unset!') unless @b
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field c is unset!') unless @c
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field x1 is unset!') unless @x1
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field x2 is unset!') unless @x2
  end

  ::Thrift::Struct.generate_accessors self
end

