/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>
#include <string.h>
#include <limits.h>


double
rpc_calc_1(char *host, double arg1, char *operacion, double arg2)
{
	CLIENT *clnt;
	double  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operacion[0]){
		case '+':
			printf("Sumamos");
			result = suma_1(arg1,arg2,clnt);
		break;
		case '-':
			printf("Restamos");
			result = resta_1(arg1,arg2,clnt);
		break;
		case 'x':
			printf("Multiplicamos");
			result = producto_1(arg1,arg2,clnt);
		break;
		case ':':
			printf("Dividimos");
			result = cociente_1(arg1,arg2,clnt);
		break;
		default:
			clnt_perror (clnt, "Operación inválida. Aceptamos -> [+,-,x,:]");
		break;
	}


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return *result;
}

funcion_cuadratica
rpc_calc_quadratic(char *host, double arg1, double arg2, double arg3)
{
	CLIENT *clnt;
	funcion_cuadratica *result;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Ecuación de segundo grado:\n");
	result = ecuaciongradodos_1(arg1,arg2,arg3,clnt);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	funcion_cuadratica resultado = *result ;

	return resultado;
}

double rpc_calc_acumulative(char *host, secuencia vectorAcumulado, char *operacion){
	CLIENT *clnt;
	double *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	switch(operacion[0]){
		case '+':
			printf("Sumamos");
			result = sumaacumuladavector_1(vectorAcumulado,clnt);
		break;
		case '-':
			printf("Restamos");
			result = restaacumuladavector_1(vectorAcumulado,clnt);
		break;
		case 'x':
			printf("Multiplicamos");
			result = productoacumuladavector_1(vectorAcumulado,clnt);
		break;
		default:
			clnt_perror (clnt, "Operación inválida. Aceptamos -> [+,-,x]");
		break;
	}


	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return *result;
}

secuencia rpc_calc_vectorial(char *host, secuencia vector1, char *operacion, secuencia vector2){
	CLIENT *clnt;
	secuencia *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	if (vector1.secuencia_len != vector2.secuencia_len)
	{
		clnt_perror (clnt, "Las longitudes deben ser iguales.");
	}
	

	else switch(operacion[0]){
		case '+':
			printf("Sumamos");
			result = sumavectores_1(vector1, vector2,clnt);
		break;
		case '-':
			printf("Restamos");
			result = restavectores_1(vector1, vector2,clnt);
		break;
		case 'x':
			printf("Multiplicamos");
			result = productovectores_1(vector1, vector2,clnt);
		break;
		case ':':
			printf("Dividimos");
			result = cocientevectores_1(vector1, vector2,clnt);
		break;
		default:
			clnt_perror (clnt, "Operación inválida. Aceptamos -> [+,-,x,:]");
		break;
	}


	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return *result;
}

matriz rpc_calc_matricial(char *host, matriz matriz1, char *operacion, matriz matriz2){
	CLIENT *clnt;
	matriz *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	

	else switch(operacion[0]){
		case '+':
			printf("Sumamos");	
			if (matriz1.matriz_len != matriz2.matriz_len || matriz1.matriz_val[0].secuencia_len != matriz2.matriz_val[0].secuencia_len)
			{
				clnt_perror (clnt, "Las dimensiones deben ser iguales.");
			}
			else
				result = sumamatrices_1(matriz1, matriz2,clnt);
		break;
		case '-':
		printf("Restamos");
			if (matriz1.matriz_len != matriz2.matriz_len || matriz1.matriz_val[0].secuencia_len != matriz2.matriz_val[0].secuencia_len)
			{
				clnt_perror (clnt, "Las dimensiones deben ser iguales.");
			}
			else 
				result = restamatrices_1(matriz1, matriz2,clnt);
		break;
		case 'x':
			printf("Multiplicamos");
			result = productomatrices_1(matriz1, matriz2,clnt);
		break;
		default:
			clnt_perror (clnt, "Operación inválida. Aceptamos -> [+,-,x]");
		break;
	}


	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return *result;
}

double rpc_calc_determinante(char *host, matriz matrizOriginal){
	CLIENT *clnt;
	double *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, RPC_CALC, DIRVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	result = determinantematrices_1(matrizOriginal,clnt);


	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return *result;
}

secuencia read_ints (const char* file_name)
{
  FILE* file = fopen (file_name, "r");
  secuencia vector_resultado;
  int i = 0;
  int iterador = 0;

  fscanf (file, "%d", &i);
  vector_resultado.secuencia_len = i;   
  printf ("Tamaño -> %d :", vector_resultado.secuencia_len); 
  vector_resultado.secuencia_val = malloc(vector_resultado.secuencia_len * sizeof(double));
  while (!feof (file))
    {  
      fscanf (file, "%d", &i);  
	  vector_resultado.secuencia_val[iterador] = i ;
	  iterador++; 
    }
  fclose (file);  

  return vector_resultado;      
}

matriz read_matrix (const char* file_name)
{
  FILE* file = fopen (file_name, "r");
  matriz matriz_resultado;
  int filas, columnas ;
  int i = 0;
  int iterador = 0;

  fscanf (file, "%d", &i);
  filas = i ;
  fscanf (file, "%d", &i);
  columnas = i;
  printf ("Tamaño de matriz-> %d x %d :\n", filas, columnas); 

  matriz_resultado.matriz_len = filas;
  matriz_resultado.matriz_val = malloc(columnas * sizeof(secuencia)) ;

  for (int sec = 0 ; sec < matriz_resultado.matriz_len ; sec++){
	  secuencia fila;
	  fila.secuencia_len = columnas ;
	  fila.secuencia_val = malloc(columnas * sizeof(double));
	  matriz_resultado.matriz_val[sec] = fila ;
  }
  
  while (!feof (file))
    {  
      fscanf (file, "%d", &i);  
	  matriz_resultado.matriz_val[(int)(iterador/filas)].secuencia_val[(int)(iterador%filas)] = i;
	  iterador++; 
    }
  fclose (file);  

  return matriz_resultado;      
}

void liberarVector (secuencia aBorrar){
	aBorrar.secuencia_len = 0;
	free(aBorrar.secuencia_val);
}

void liberarMatriz (matriz aBorrar){
	for (int i = 0 ; i < aBorrar.matriz_len ; i++){
		liberarVector(aBorrar.matriz_val[i]);
	}
	aBorrar.matriz_len = 0;
	free(aBorrar.matriz_val);
}


int
main (int argc, char *argv[])
{
	char *host;
	char *operacion;
	double operando1;
	double operando2;
	double operando3;
	double resultado;
	funcion_cuadratica solucion;
	secuencia vector1 ;
	secuencia vector2 ;
	secuencia vector_solucion;
	matriz matriz1 ;
	matriz matriz2 ;
	matriz matriz_solucion;

	if (argc < 4) {
		printf ("Calculadora básica: %s <Host_server> <Operando1> <Operación> <Operando2> \n", argv[0]);
		printf ("Resolutor de ecuaciones: %s <Host_server> -s <Ax^2> <Bx> <C> \n", argv[0]);
		printf ("Calculadora de operaciones acumuladas (Suma, Resta, Producto): %s <Host_server> -v1 <Archivo_vector> <Operacion> \n", argv[0]);
		printf ("Calculadora vectorial : %s <Host_server> -v2 <Archivo_vector1> <Operacion> <Archivo_vector2>\n", argv[0]);
		printf ("Calculadora de determinante de matrices: %s <Host_server> -dm <Archivo_matriz>\n", argv[0]);
		printf ("Calculadora matricial (Suma, Resta, Producto): %s <Host_server> -m2 <Archivo_matriz1> <Operacion> <Archivo_matriz2> \n", argv[0]);
		exit (1);
	}

	if(argc == 4 && strcmp(argv[2],"-dm") == 0){
		host = argv[1];
		char *filename = argv[3] ;
		matriz1 = read_matrix(filename);
		resultado = rpc_calc_determinante(host,matriz1);
		printf ("\n%s -> Determinante = %f \n", host, resultado);
		liberarMatriz(matriz1);
	}

	else if (argc == 5 && strcmp(argv[2],"-v1") == 0){
		host = argv[1];
		char *filename = argv[3] ;
		operacion = argv[4];
		vector1 = read_ints(filename);
		resultado = rpc_calc_acumulative(host,vector1,operacion);
		printf ("\n%s -> Operación acumulada [%s] = %f \n", host, operacion, resultado);
		liberarVector(vector1);
	}

	else if (argc == 6 && strcmp(argv[2],"-v2") == 0){
		host = argv[1];
		char *filename1 = argv[3] ;
		char *filename2 = argv[5] ;
		operacion = argv[4];
		vector1 = read_ints(filename1);
		vector2 = read_ints(filename2);
		vector_solucion = rpc_calc_vectorial(host,vector1,operacion,vector2);
		printf ("\n%s -> Operación vectorial [%s] =\n", host, operacion);
		printf("[");
		for (int i = 0 ; i < vector_solucion.secuencia_len ; i++){
			printf(" %f ", vector_solucion.secuencia_val[i]);
		}
		printf("]\n\n");

		liberarVector(vector1);
		liberarVector(vector2);
		liberarVector(vector_solucion);
	}

	else if (argc == 6 && strcmp(argv[2],"-m") == 0){
		host = argv[1];
		char *filename1 = argv[3] ;
		char *filename2 = argv[5] ;
		operacion = argv[4];
		matriz1 = read_matrix(filename1);
		matriz2 = read_matrix(filename2);
		matriz_solucion = rpc_calc_matricial(host,matriz1,operacion,matriz2);
		printf ("\n%s -> Operación vectorial [%s] =\n", host, operacion);
		
		for (int i = 0 ; i < matriz1.matriz_len ; i++){
			printf("[");
			for (int j = 0; j < matriz1.matriz_val[i].secuencia_len; j++)
			{
				printf(" %f ",matriz1.matriz_val[i].secuencia_val[j]);
			}
			printf("]\n");
		}
		printf("\n\n");

		for (int i = 0 ; i < matriz2.matriz_len ; i++){
			printf("[");
			for (int j = 0; j < matriz2.matriz_val[i].secuencia_len; j++)
			{
				printf(" %f ",matriz2.matriz_val[i].secuencia_val[j]);
			}
			printf("]\n");
		}
		printf("\n\n");

		printf("Resultado: \n");
		for (int i = 0 ; i < matriz_solucion.matriz_len ; i++){
			printf("[");
			for (int j = 0; j < matriz_solucion.matriz_val[i].secuencia_len; j++)
			{
				printf(" %f ",matriz_solucion.matriz_val[i].secuencia_val[j]);
			}
			printf("]\n");
		}
		printf("\n\n");
		
		liberarMatriz(matriz1);
		liberarMatriz(matriz2);
		liberarMatriz(matriz_solucion);
	}

	else if (argc == 5){
		host = argv[1];
		operacion = argv[3];
		operando1 = atoi(argv[2])*1.0;
		operando2 = atoi(argv[4])*1.0;
		printf ("Operación a %s -> %f %s %f \n", host, operando1, operacion, operando2);

		resultado = rpc_calc_1 (host,operando1,operacion,operando2);

		printf ("\n%s -> %f %s %f = %f \n", host, operando1, operacion, operando2, resultado);
	}

	else if (argc == 6 && strcmp(argv[2],"-s") == 0){
		host = argv[1];
		operando1 = atoi(argv[3]);
		operando2 = atoi(argv[4]);
		operando3 = atoi(argv[5]);
		solucion = rpc_calc_quadratic (host,operando1,operando2,operando3);

		if(solucion.valor_1 == INT_MIN || solucion.valor_2 == INT_MIN)
			printf ("\n%s : Para la ecuación %dx^2 + %dx + %d = 0 -> No hay soluciones reales \n", host, solucion.a, solucion.b, solucion.c);
		else
			printf ("\n%s : Para la ecuación %dx^2 + %dx + %d = 0 -> {X1 = %f , X2 = %f} \n", host, solucion.a, solucion.b, solucion.c, solucion.valor_1, solucion.valor_2);
	}

	else{
		printf ("Calculadora básica: %s <Host_server> <Operando1> <Operación> <Operando2> \n", argv[0]);
		printf ("Resolutor de ecuaciones: %s <Host_server> -s <Ax^2> <Bx> <C> \n", argv[0]);
		printf ("Calculadora de operaciones acumuladas (Suma, Resta, Producto): %s <Host_server> -v1 <Archivo_vector> <Operacion> \n", argv[0]);
		printf ("Calculadora vectorial : %s <Host_server> -v2 <Archivo_vector1> <Operacion> <Archivo_vector2>\n", argv[0]);
		printf ("Calculadora de determinante de matrices: %s <Host_server> -dm <Archivo_matriz>\n", argv[0]);
		printf ("Calculadora matricial (Suma, Resta, Producto): %s <Host_server> -m2 <Archivo_matriz1> <Operacion> <Archivo_matriz2> \n", argv[0]);
		exit (1);
	}
	
exit (0);
}
