/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
suma_1(double arg1, double arg2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
resta_1(double arg1, double arg2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, resta, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
producto_1(double arg1, double arg2,  CLIENT *clnt)
{
	producto_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, producto, (xdrproc_t) xdr_producto_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
cociente_1(double arg1, double arg2,  CLIENT *clnt)
{
	cociente_1_argument arg;
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, cociente, (xdrproc_t) xdr_cociente_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

funcion_cuadratica *
ecuaciongradodos_1(int arg1, int arg2, int arg3,  CLIENT *clnt)
{
	ecuaciongradodos_1_argument arg;
	static funcion_cuadratica clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, ecuacionGradoDos, (xdrproc_t) xdr_ecuaciongradodos_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_funcion_cuadratica, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
sumaacumuladavector_1(secuencia arg1,  CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sumaAcumuladaVector,
		(xdrproc_t) xdr_secuencia, (caddr_t) &arg1,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
restaacumuladavector_1(secuencia arg1,  CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, restaAcumuladaVector,
		(xdrproc_t) xdr_secuencia, (caddr_t) &arg1,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
productoacumuladavector_1(secuencia arg1,  CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, productoAcumuladaVector,
		(xdrproc_t) xdr_secuencia, (caddr_t) &arg1,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

secuencia *
sumavectores_1(secuencia arg1, secuencia arg2,  CLIENT *clnt)
{
	sumavectores_1_argument arg;
	static secuencia clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, sumaVectores, (xdrproc_t) xdr_sumavectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_secuencia, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

secuencia *
restavectores_1(secuencia arg1, secuencia arg2,  CLIENT *clnt)
{
	restavectores_1_argument arg;
	static secuencia clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, restaVectores, (xdrproc_t) xdr_restavectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_secuencia, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

secuencia *
productovectores_1(secuencia arg1, secuencia arg2,  CLIENT *clnt)
{
	productovectores_1_argument arg;
	static secuencia clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, productoVectores, (xdrproc_t) xdr_productovectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_secuencia, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

secuencia *
cocientevectores_1(secuencia arg1, secuencia arg2,  CLIENT *clnt)
{
	cocientevectores_1_argument arg;
	static secuencia clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, cocienteVectores, (xdrproc_t) xdr_cocientevectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_secuencia, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matriz *
sumamatrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	sumamatrices_1_argument arg;
	static matriz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, sumaMatrices, (xdrproc_t) xdr_sumamatrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matriz *
restamatrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	restamatrices_1_argument arg;
	static matriz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, restaMatrices, (xdrproc_t) xdr_restamatrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matriz *
productomatrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	productomatrices_1_argument arg;
	static matriz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, productoMatrices, (xdrproc_t) xdr_productomatrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
determinantematrices_1(matriz arg1,  CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, determinanteMatrices,
		(xdrproc_t) xdr_matriz, (caddr_t) &arg1,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
