/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_producto_1 (producto_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_cociente_1 (cociente_1_argument *argp, struct svc_req *rqstp)
{
	return (cociente_1_svc(argp->arg1, argp->arg2, rqstp));
}

static funcion_cuadratica *
_ecuaciongradodos_1 (ecuaciongradodos_1_argument *argp, struct svc_req *rqstp)
{
	return (ecuaciongradodos_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static double *
_sumaacumuladavector_1 (secuencia  *argp, struct svc_req *rqstp)
{
	return (sumaacumuladavector_1_svc(*argp, rqstp));
}

static double *
_restaacumuladavector_1 (secuencia  *argp, struct svc_req *rqstp)
{
	return (restaacumuladavector_1_svc(*argp, rqstp));
}

static double *
_productoacumuladavector_1 (secuencia  *argp, struct svc_req *rqstp)
{
	return (productoacumuladavector_1_svc(*argp, rqstp));
}

static secuencia *
_sumavectores_1 (sumavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static secuencia *
_restavectores_1 (restavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (restavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static secuencia *
_productovectores_1 (productovectores_1_argument *argp, struct svc_req *rqstp)
{
	return (productovectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static secuencia *
_cocientevectores_1 (cocientevectores_1_argument *argp, struct svc_req *rqstp)
{
	return (cocientevectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matriz *
_sumamatrices_1 (sumamatrices_1_argument *argp, struct svc_req *rqstp)
{
	return (sumamatrices_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matriz *
_restamatrices_1 (restamatrices_1_argument *argp, struct svc_req *rqstp)
{
	return (restamatrices_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matriz *
_productomatrices_1 (productomatrices_1_argument *argp, struct svc_req *rqstp)
{
	return (productomatrices_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_determinantematrices_1 (matriz  *argp, struct svc_req *rqstp)
{
	return (determinantematrices_1_svc(*argp, rqstp));
}

static void
rpc_calc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		producto_1_argument producto_1_arg;
		cociente_1_argument cociente_1_arg;
		ecuaciongradodos_1_argument ecuaciongradodos_1_arg;
		secuencia sumaacumuladavector_1_arg;
		secuencia restaacumuladavector_1_arg;
		secuencia productoacumuladavector_1_arg;
		sumavectores_1_argument sumavectores_1_arg;
		restavectores_1_argument restavectores_1_arg;
		productovectores_1_argument productovectores_1_arg;
		cocientevectores_1_argument cocientevectores_1_arg;
		sumamatrices_1_argument sumamatrices_1_arg;
		restamatrices_1_argument restamatrices_1_arg;
		productomatrices_1_argument productomatrices_1_arg;
		matriz determinantematrices_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case producto:
		_xdr_argument = (xdrproc_t) xdr_producto_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _producto_1;
		break;

	case cociente:
		_xdr_argument = (xdrproc_t) xdr_cociente_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _cociente_1;
		break;

	case ecuacionGradoDos:
		_xdr_argument = (xdrproc_t) xdr_ecuaciongradodos_1_argument;
		_xdr_result = (xdrproc_t) xdr_funcion_cuadratica;
		local = (char *(*)(char *, struct svc_req *)) _ecuaciongradodos_1;
		break;

	case sumaAcumuladaVector:
		_xdr_argument = (xdrproc_t) xdr_secuencia;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _sumaacumuladavector_1;
		break;

	case restaAcumuladaVector:
		_xdr_argument = (xdrproc_t) xdr_secuencia;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _restaacumuladavector_1;
		break;

	case productoAcumuladaVector:
		_xdr_argument = (xdrproc_t) xdr_secuencia;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _productoacumuladavector_1;
		break;

	case sumaVectores:
		_xdr_argument = (xdrproc_t) xdr_sumavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_secuencia;
		local = (char *(*)(char *, struct svc_req *)) _sumavectores_1;
		break;

	case restaVectores:
		_xdr_argument = (xdrproc_t) xdr_restavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_secuencia;
		local = (char *(*)(char *, struct svc_req *)) _restavectores_1;
		break;

	case productoVectores:
		_xdr_argument = (xdrproc_t) xdr_productovectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_secuencia;
		local = (char *(*)(char *, struct svc_req *)) _productovectores_1;
		break;

	case cocienteVectores:
		_xdr_argument = (xdrproc_t) xdr_cocientevectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_secuencia;
		local = (char *(*)(char *, struct svc_req *)) _cocientevectores_1;
		break;

	case sumaMatrices:
		_xdr_argument = (xdrproc_t) xdr_sumamatrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_matriz;
		local = (char *(*)(char *, struct svc_req *)) _sumamatrices_1;
		break;

	case restaMatrices:
		_xdr_argument = (xdrproc_t) xdr_restamatrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_matriz;
		local = (char *(*)(char *, struct svc_req *)) _restamatrices_1;
		break;

	case productoMatrices:
		_xdr_argument = (xdrproc_t) xdr_productomatrices_1_argument;
		_xdr_result = (xdrproc_t) xdr_matriz;
		local = (char *(*)(char *, struct svc_req *)) _productomatrices_1;
		break;

	case determinanteMatrices:
		_xdr_argument = (xdrproc_t) xdr_matriz;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _determinantematrices_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPC_CALC, DIRVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_CALC, DIRVER, rpc_calc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPC_CALC, DIRVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_CALC, DIRVER, rpc_calc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPC_CALC, DIRVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
