/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_secuencia (XDR *xdrs, secuencia *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->secuencia_val, (u_int *) &objp->secuencia_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matriz (XDR *xdrs, matriz *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matriz_val, (u_int *) &objp->matriz_len, ~0,
		sizeof (secuencia), (xdrproc_t) xdr_secuencia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_funcion_cuadratica (XDR *xdrs, funcion_cuadratica *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->a);
		IXDR_PUT_LONG(buf, objp->b);
		IXDR_PUT_LONG(buf, objp->c);
		}
		 if (!xdr_double (xdrs, &objp->valor_1))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->valor_2))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->a))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->b))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->c))
				 return FALSE;

		} else {
		objp->a = IXDR_GET_LONG(buf);
		objp->b = IXDR_GET_LONG(buf);
		objp->c = IXDR_GET_LONG(buf);
		}
		 if (!xdr_double (xdrs, &objp->valor_1))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->valor_2))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor_1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor_2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_1_argument (XDR *xdrs, resta_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_1_argument (XDR *xdrs, producto_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cociente_1_argument (XDR *xdrs, cociente_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ecuaciongradodos_1_argument (XDR *xdrs, ecuaciongradodos_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumavectores_1_argument (XDR *xdrs, sumavectores_1_argument *objp)
{
	 if (!xdr_secuencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_secuencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restavectores_1_argument (XDR *xdrs, restavectores_1_argument *objp)
{
	 if (!xdr_secuencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_secuencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_productovectores_1_argument (XDR *xdrs, productovectores_1_argument *objp)
{
	 if (!xdr_secuencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_secuencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cocientevectores_1_argument (XDR *xdrs, cocientevectores_1_argument *objp)
{
	 if (!xdr_secuencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_secuencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumamatrices_1_argument (XDR *xdrs, sumamatrices_1_argument *objp)
{
	 if (!xdr_matriz (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_matriz (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restamatrices_1_argument (XDR *xdrs, restamatrices_1_argument *objp)
{
	 if (!xdr_matriz (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_matriz (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_productomatrices_1_argument (XDR *xdrs, productomatrices_1_argument *objp)
{
	 if (!xdr_matriz (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_matriz (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
